server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml  #mybatis配置文件所在目录
  type-aliases-package: com.bob.cloud.entity  #所有entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml #Mapper映射文件

spring:
  application:
    name: cloud-dept  # 负载均衡会用到
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    druid:
        min-idle: 5 #数据库连接池的最小维持连接数
        initial-size: 5 #初始化连接数
        max-active: 20  #数据库连接池的最大维持连接数
        max-wait: 60000 # 配置获取连接等待超时的时间
        time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
        validation-query: select 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        driver-class-name: org.gjt.mm.mysql.Driver  #MySQL驱动包
        url: jdbc:mysql://192.168.174.8:3306/cloudDB01 #数据库名称
        username: root
        password: bob225812

# eureka集群配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: CLOUD-DEPT-8001 #主机名称：服务名称，需要唯一
    prefer-ip-address: true      #访问信息有IP信息提示

# 服务信息
info:
  app.name: CLOUD-DEPT-8001
  company.name: huatai
  build.artifactId: $project.artifactId$
  build.version: $project.version$

